#!/usr/bin/env ruby

require 'colorize'

class Sherevo
  HOME = ENV['HOME']
  PROJECT_DIRECTORY = "#{HOME}/workspace/sotd/"
  SHEREVO_FILE = 'sotd.txt'
  ABSOLUTE_PATH = PROJECT_DIRECTORY + SHEREVO_FILE

  COLORS = [:red, :blue, :light_blue, :green, ]

  def initialize
    sherevo
  end 

  private 

  def content
    @content ||= File.readlines(ABSOLUTE_PATH).shuffle
  end

  def sherevo_of_the_day
    content.sample
  end

  def random_color
    String.colors.sample
  end

  def sherevo
    puts sherevo_of_the_day.colorize(color: random_color, mode: :bold)
  end
end 

Sherevo.new 


