#!/usr/bin/env ruby

require 'colorize'

class Sherevo
  SHEREVO_FILE = 'sotd.txt'
  COLORS = [:red, :blue, :light_blue, :green, ]

  def initialize
    sherevo
  end 

  private 

  def content
    @content ||= File.readlines(SHEREVO_FILE).shuffle
  end

  def sherevo_of_the_day
    content.sample
  end

  def random_color
    String.colors.sample
  end

  def sherevo
    puts sherevo_of_the_day.colorize(color: random_color, mode: :bold)
  end
end 

Sherevo.new 


